version: '3'

networks:

  default:

services:

  cluster:
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/service
    networks:
      - default
    tty: true
