version: '3'

networks:
  default:

services:
  cicflowmeter:
    build:
      context: .
      dockerfile: ./CICFlowMeter/Dockerfile
    volumes:
      - ./CICFlowMeter:/CICFlowMeter
    networks:
      - default
    tty: true

  minimumfeaturizer:
    build:
      context: .
      dockerfile: ./MinimumFeaturizer/Dockerfile
    volumes:
      - ./MinimumFeaturizer:/MinimumFeaturizer
    networks:
      - default
    tty: true

  netdetect:
    build:
      context: .
      dockerfile: ./NetDetect/Dockerfile
    volumes:
      - ./NetDetect:/NetDetect
    networks:
      - default
    tty: true

