version: '3'

networks:
  default:

services:
  netdetect1:
    build:
      context: .
      dockerfile: ./NetDetect/Dockerfile
    volumes:
      - ./NetDetect/datasets:/NetDetect/datasets
    command: sh -c "python3 NetDetect/param_gen.py -dice 0 -total 5 | bash"
    tty: true

  netdetect2:
    build:
      context: .
      dockerfile: ./NetDetect/Dockerfile
    volumes:
      - ./NetDetect/datasets:/NetDetect/datasets
    command: sh -c "python3 NetDetect/param_gen.py -dice 1 -total 5 | bash"
    tty: true

  netdetect3:
    build:
      context: .
      dockerfile: ./NetDetect/Dockerfile
    volumes:
      - ./NetDetect/datasets:/NetDetect/datasets
    command: sh -c "python3 NetDetect/param_gen.py -dice 2 -total 5 | bash"
    tty: true

  netdetect4:
    build:
      context: .
      dockerfile: ./NetDetect/Dockerfile
    volumes:
      - ./NetDetect/datasets:/NetDetect/datasets
    command: sh -c "python3 NetDetect/param_gen.py -dice 3 -total 5 | bash"
    tty: true

  netdetect5:
    build:
      context: .
      dockerfile: ./NetDetect/Dockerfile
    volumes:
      - ./NetDetect/datasets:/NetDetect/datasets
    command: sh -c "python3 NetDetect/param_gen.py -dice 4 -total 5 | bash"
    tty: true

